version: '3'

services:
  eureka-server:
    image: eureka-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8762:8761"  
    networks:
      - eureka-network
    restart: always

networks:
  eureka-network:
    driver: bridge
